apiVersion: apps/v1
kind: Deployment
metadata:
  name: ida-operator
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 25.0.8
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ida-operator
  template:
    metadata:
      labels:
        name: ida-operator
    spec:
      containers:
        - name: operator
          image: <IDA_OPERATOR_IMAGE>
          imagePullPolicy: IfNotPresent
          args:
            - --metrics-bind-address=127.0.0.1:8080
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      imagePullSecrets:
        - name: <IMAGE_PULL_SECRET>
      terminationGracePeriodSeconds: 10
      serviceAccountName: ida-operator
