apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ida-operator
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 24.0.9
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ida-operator
subjects:
  - kind: ServiceAccount
    name: ida-operator
