apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <NAMESPACE>-ida-operator
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 24.0.8.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ida-operator
subjects:
  - kind: ServiceAccount
    name: ida-operator
    namespace: <NAMESPACE>
