apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ida-installer
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumes
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - deployments/scale
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - use
  - apiGroups:
      - ""
    resources:
      - securitycontextconstraints
      - namespaces
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - '*'
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
     - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
  - apiGroups:
      - sdc.ibm.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - delete