apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{.Release.Name}}-hazelcast-role"
rules:
  - apiGroups:
      - ""
      # Access to apps API is only required to support automatic cluster state management
      # when persistence (hot-restart) is enabled.
      - apps
    resources:
      - endpoints
      - pods
      - nodes
      - services
      # Access to statefulsets resource is only required to support automatic cluster state management
      # when persistence (hot-restart) is enabled.
      - statefulsets
    verbs:
      - get
      - list
      # Watching resources is only required to support automatic cluster state management
      # when persistence (hot-restart) is enabled.
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{.Release.Name}}-hazelcast-role-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{.Release.Name}}-hazelcast-role"
subjects:
  - kind: ServiceAccount
    name: default