apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ida-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <STORAGE_CLASS_NAME>
  resources:
    requests:
      storage: 5Gi
