apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  prefixName: idadeploy

  idaDatabase:
    type: postgres
    internalDatabase:
      enabled: true
      image: postgres:14.3
      imagePullPolicy: Always
      imagePullSecrets:
      configMapVolume: ida-embedded-db-configmap
      existingPVCName: ida-db-pvc
    externalDatabase:
      enabled: false

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    pvcName: ida-data-pvc
    replicas: 1
    jvmArgs: "-Dhazelcast.diagnostics.enabled=true -Dhazelcast.kube.service.name=idadeploy-ida-web -Dhazelcast.kube.namespace=<NAMESPACE>"
    waitIDADB:
      image: busybox:1.28
