apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  shared:
    storageClassName: 
  idaDatabase:
    type: postgres
    internal:
      enabled: false
    external:
      enabled: true
      #For Oracle only.
      databaseUrl:
      databaseName:
      databasePort:
      databaseServerName:
      currentSchema:
      # The secret for database username and password
      databaseCredentialSecret: ida-external-db-credential

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    replicas: 1
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
    storage:
      storageCapacity: 5Gi
      existingDataPVCName:
    initContainer:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
    tlsCertSecret:
    trustedCertSecret:
    network:
      type:  
