apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  shared:
    storageClassName: 
  idaDatabase:
    type: postgres
    internal:
      enabled: true
      image: postgres:14.3
      imagePullPolicy: Always
      imagePullSecrets:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
      storage:
        existingDBPVCName: 
    external:
      enabled: false

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    replicas: 1
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    storage:
      storageCapacity: 5Gi
      existingDataPVCName:
    initContainer:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
    tlsCertSecret:
    trustedCertSecret:
    network:
      type:  
