apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  prefixName: idadeploy

  idaDatabase:
    type: postgres
    internal:
      enabled: false
    external:
      enabled: true
      secretCredentials: ida-external-db-secret

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    pvcName: ida-data-pvc
    replicas: 1
    waitIDADB:
      image: busybox:1.28