apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: ida-demo
spec:
  prefixName: ida-demo

  idaDatabase:
    type: mysql
    internalDatabase:
      enabled: true
      image: mysql:5.7
      imagePullPolicy: Always
      imagePullSecrets:
      configMapVolume: ida-embedded-db-configmap
      existingPVCName: ida-db-pvc
    externalDatabase:
      enabled: false

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    pvcName: ida-data-pvc
    replicas: 1
    waitIDADB:
      image: busybox:1.28
