apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  prefixName: idadeploy

  idaDatabase:
    type: mysql
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      secretCredentials: ida-external-db-secret

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    pvcName: ida-data-pvc
    replicas: 1
    jvmArgs: "-Dhazelcast.diagnostics.enabled=true -Dhazelcast.kube.service.name=idadeploy-ida-web -Dhazelcast.kube.namespace=<NAMESPACE>"
    waitIDADB:
      image: busybox:1.28
