apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  prefixName: idadeploy

  idaDatabase:
    type: postgres
    internal:
      enabled: true
      image: postgres:14.3
      imagePullPolicy: Always
      imagePullSecrets:
      existingPVCName: ida-db-pvc
    external:
      enabled: false

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    pvcName: ida-data-pvc
    replicas: 1
    cpuLimit: 4
    cpuRequest: 2
    memoryLimit: 8Gi
    memoryRequest: 4Gi
    tlsCert:
    waitIDADB:
      image: busybox:1.28
