apiVersion: sdc.ibm.com/v1
kind: IDACluster
metadata:
  name: idadeploy
spec:
  shared:
    storageClassName: 
  idaDatabase:
    type: postgres
    internal:
      enabled: false
    external:
      enabled: true
      #For Oracle only.
      databaseUrl:
      databaseName:
      databasePort:
      databaseServerName:
      currentSchema:
      # The secret for database username and password
      databaseCredentialSecret: ida-external-db-secret

  idaWeb:
    image: <IDA_IMAGE>
    imagePullPolicy: Always
    imagePullSecrets:
    replicas: 1
    resources:
      cpuLimit: 4
      cpuRequest: 2
      memoryLimit: 8Gi
      memoryRequest: 4Gi
    storage:
      storageCapacity: 5Gi
      existingDataPVCName:
    tlsCert:
    tlsCertPassword:
    waitIDADB:
      image: busybox:1.28