apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ida-operator
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 1.0.5
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - use
  - apiGroups:
      - ""
    resources:
      - securitycontextconstraints
      - namespaces
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sdc.ibm.com
    resources:
      - '*'
    verbs:
      - '*'
