kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ida-operators-edit
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 24.0.5
rules:
  - apiGroups:
      - sdc.ibm.com
    resources:
      - '*'
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
      - watch