apiVersion: apps/v1
kind: Deployment
metadata:
  name: ida-operator
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ida-operator
  template:
    metadata:
      labels:
        name: ida-operator
    spec:
      containers:
        - name: operator
          image: image-registry.openshift-image-registry.svc:5000/ida/ida-operator:1.0.0
          args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
            - --leader-election-id=op-ida
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 60Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: ida-operator
