apiVersion: apps/v1
kind: Deployment
metadata:
  name: ida-operator
  labels:
    app.kubernetes.io/instance: ida
    app.kubernetes.io/managed-by: ida
    app.kubernetes.io/name: ida
    release: 23.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ida-operator
  template:
    metadata:
      labels:
        name: ida-operator
    spec:
      containers:
        - name: operator
          image: ctesdc/ida-operator:23.0.2
          imagePullPolicy: Always
          args:
            - --metrics-addr=127.0.0.1:8080
      imagePullSecrets:
        - name: <IMAGE_PULL_SECRET>
      terminationGracePeriodSeconds: 10
      serviceAccountName: ida-operator
